### ISSUE TITLE
How do I install?

### ISSUE THREAD

**Issue by kennygokh** [ozntel/obsidian-msg-handler#1]
Hi, I would like to try the plug-in, how do I install it?

**Comment by ozntel** [comment]
You can install **Obsidian42 - BRAT** plugin, which will make it easier for you to install beta plugins. Once you install, go to the settings of BRAT and use the "Add Beta Plugin" option and provide the repo link: https://github.com/ozntel/obsidian-msg-handler
Once it is installed, remember to enable the plugin. That's it.
